spring:
  application:
    name: KafkaAuth
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:9092}

app:
  openapi:
    dev-url: http://localhost:8088
  kafka:
    topic:
      userInitRegistration: "user-init-register-topic"
      userConfirmRegistration: "user-confirm-register-topic"
    kafkaMessageGroupId: "kafka-message-group-id-2"
    listener:
      confirm-code-event: ${KAFKA_LISTENERS_ENABLED:false}
  security:
    jwt:
      secret-key: 7738782F425432A462D413F44284614E7235757635266556A5867217AAE32743
      expiration: 86400000 # a day
      #      expiration: 120 # a day
      refresh-token:
        expiration: 604800000 # 7 days
#        expiration: 240 # 7 days
server:
  port: 8088